#cloud-config
  
# create user ${username}
users:
  - name: "${username}"
    gecos: "${username}"
    homedir: "/home/${username}"
    primary_group: "${username}"
    shell: "/bin/bash"
    ssh_authorized_keys:
      - "${ssh-public-key}"
    sudo: "ALL= (ALL) NOPASSWD"

write_files:
  - path: "/home/${username}/.ssh/${ssh-private-key-filename}"
    content: ${jsonencode(ssh-private-key)}
    owner: "${username}"
    permissions: "0400"
    append: false
    defer: true

final_message: "cloud-init version $VERSION has completed at $TIMESTAMP after $UPTIME using $DATASOURCE"

