
# install docker
packages:
    - docker.io
    - docker-compose
package_update: true
package_upgrade: true
package_reboot_if_required: true

# create the docker group and add user ${username}
groups: 
  - docker

runcmd:
  - git clone https://github.com/webpwnized/mutillidae-dockerhub.git /home/${username}/mutillidae-dockerhub
  - sed -i 's/127.0.0.1://g' /home/${username}/mutillidae-dockerhub/docker-compose.yml
  - chown -R ${username}:${username} /home/${username}/mutillidae-dockerhub
  - sudo -u ${username} docker-compose -f /home/${username}/mutillidae-dockerhub/docker-compose.yml up -d

final_message: "cloud-init version $VERSION has completed at $TIMESTAMP after $UPTIME using $DATASOURCE"

