#cloud-config
  
# create user jeremy
users:
  - name: jeremy
    gecos: "Jeremy Druin"
    homedir: "/home/jeremy"
    primary_group: "jeremy"
    shell: "/bin/bash"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHuz17wgiGT9Ynz5R4FEdnAn4nhmg3HB/SOq42OBeaoN jeremy@host.local"
    sudo: "ALL= (ALL) NOPASSWD"

write_files:
  - path: "/home/jeremy/.ssh/${filename}"
    content: ${jsonencode(content)}
    owner: "jeremy"
    permissions: "0400"
    append: false
    defer: true

final_message: "cloud-init version $VERSION has completed at $TIMESTAMP after $UPTIME using $DATASOURCE"

