#cloud-config

# install ping software
packages:
    - inetutils-ping
package_update: true
package_upgrade: true
package_reboot_if_required: true

# create user ${username}
users:
  - name: "${username}"
    gecos: "${username}"
    homedir: "/home/${username}"
    primary_group: "${username}"
    shell: "/bin/bash"
    #We do not need to pass the public key when using OS Login
    #ssh_authorized_keys:
        #- "$#{ssh-public-key}"
    sudo: "ALL= (ALL) NOPASSWD"

#We do not need the private key when using OS Login
#write_files:
  #- path: "/home/$#{username}/.ssh/$#{ssh-private-key-filename}"
    #content: $#{jsonencode(ssh-private-key)}
    #owner: "$#{username}"
    #permissions: "0400"
    #append: false
    #defer: true

final_message: "cloud-init version $VERSION has completed at $TIMESTAMP after $UPTIME using $DATASOURCE"

