
# write private key to file in .ssh directory and set permissions
write_files:
  - path: "/home/${username}/.ssh/${ssh-private-key-filename}"
    content: ${jsonencode(ssh-private-key)}
    owner: "${username}"
    permissions: "0400"
    append: false
    defer: true

final_message: "cloud-init version $VERSION has completed at $TIMESTAMP after $UPTIME using $DATASOURCE"

